# Generated by Django 4.1 on 2022-09-04 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexHomeScreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Captured',
            new_name='Pokemon',
        ),
    ]
